"""add_english_fields

Revision ID: 70c719428531
Revises: 3a7fc5797f1d
Create Date: 2026-06-28 01:31:13.869761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c719428531'
down_revision = '3a7fc5797f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('content_en', sa.Text(), nullable=True))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('description_en')
        batch_op.drop_column('title_en')

    with op.batch_alter_table('profile_sections', schema=None) as batch_op:
        batch_op.drop_column('content_en')
        batch_op.drop_column('title_en')

    # ### end Alembic commands ###
